### ISSUE TITLE
Question about training on imagenet

### ISSUE THREAD

**Issue by Gyiming** [yoheikikuta/adversarial-camera-stickers#2]
Very useful implementation. I'm wondering if you have tried on training on a specific class on imagenet.

I have modified your code a little bit and trained on Imagenet, however, it seems the loss wasn't reduced significantly. Also, the targeted attack was not successful as well. Do you have any comments on this issue?

**Comment by lijuncheng16** [comment]
I just happened to see the issue being still open here, would like to answer the question as I replied in the email (for public viewers whoever is interested):
The untargeted attack was the main focus of the paper. 

As for the targeted case, as I reported in the paper, the success rate is way lower than the targeted attack.

The parameters were key to success, and some classes were more robust than the other classes. e.g. traffic sign to guitar pick is a lot easier than traffic sign to cat. The intuition behind it is simple: the dots just don't have enough parameters to contain the feature of a cat so the CE loss could never get close to cats.

As far as I can recall, I also spent a lot of time tuning the targeted attacks, and that's where coordinate descent came into the picture. You need to freeze some of the parameters first to make sure loss is decreasing before you go to the next step to optimize the next parameters. (Convex optimization trick)

I remember with 6 dots the success rate was only around 30%, going up to 9 dots you can get the targeted attack success rate up, but then the image would look very "busy" --full of dots. 

That being said, the point is to demo that it's possible to fool a classifier on an autopilot system so if the "stopsign" is not recognized as stop sign anymore, then we are already succeeding as attackers.

--Juncheng (Billy) Li

**Comment by yoheikikuta** [comment]
@Gyiming 

Sorry for the late reply.

> I have modified your code a little bit and trained on Imagenet, however, it seems the loss wasn't reduced significantly. Also, the targeted attack was not successful as well. Do you have any comments on this issue?

I didn't check my implementations with various classes because my main interest was to understand the concept of this method.
So it's hard to give you useful comments.

@lijuncheng16 Thanks for your great advice!

In addition, my implementation is rather naive. 
This probably make the attacks difficult compared to the implementation of the original paper.
